server:
  port: 8080
  servlet:
    context-path: /
    session:
      cookie:
        same-site: strict
        http-only: true

spring:
  application:
    name: glamora_store
  config:
    import: "optional:file:.env[.properties]"
  datasource:
    url: ${POSTGRES_URL}
    username: ${USERNAME_DB}
    password: ${PASSWORD_DB}
  jpa:
    hibernate:
      ddl-auto: none #update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  #        envers:
  #          audit_table_suffix: _aud
  #          store_data_at_delete: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  #    baseline-version: 1
  main:
    allow-bean-definition-overriding: true

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${USERNAME_MAIL}
    password: ${PASSWORD_MAIL}
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

jwt:
  secretKey: ${JWT_SECRETKEY}
  access-token-expiration: 604800 # 300 # (seconds) == 5 minutes in seconds
  refresh-token-expiration: 604800 # 7 days in seconds

cors:
  allowed-origins: ${FRONTEND_URL}

frontend:
  url: ${FRONTEND_URL}

vnpay:
  url: ${VNPAY_URL}
  return-url: ${VNPAY_RETURN_URL}
  tmn-code: ${VNPAY_TMN_CODE}
  hash-secret: ${VNPAY_HASH_SECRET}
  version: 2.1.0
  command: pay
  order-type: other

# Scheduler Configuration
scheduler:
  payment:
    expiry-check:
      enabled: true
      cron: 0 */5 * * * * # Every 5 minutes
  refresh-token:
    cleanup:
      enabled: true
      cron: 0 0 2 * * * # Every day at 2:00 AM

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui
