server:
  port: 8080
  servlet:
    context-path: /
    session:
      cookie:
        same-site: strict
        http-only: true

spring:
  application:
    name: glamora_store
  datasource:
    url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/glamora_store}
    username: ${USERNAME_DB:postgres}
    password: ${PASSWORD_DB:1234567890}
  jpa:
    hibernate:
      ddl-auto: none #update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        envers:
          audit_table_suffix: _aud
          store_data_at_delete: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
  #    baseline-version: 1
  main:
    allow-bean-definition-overriding: true

  mail:
    host: ${MAIL_HOST:sandbox.smtp.mailtrap.io}
    port: ${MAIL_PORT:587}
    username: ${USERNAME_MAIL:nhap@gmail.com}
    password: ${PASSWORD_MAIL:nhap}

jwt:
  secretKey: "nYWEYvaGHUfhmCyygqLwaeLPYDXbv9ZX7sbRmhEuhthrQnz5WLuEyO4Gh5e9nbjT"

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui
