server:
  port: 8080
  servlet:
    context-path: /
    session:
      cookie:
        same-site: strict
        http-only: true

spring:
  application:
    name: glamora_store
  config:
    import: "optional:file:.env[.properties]"
  datasource:
    url: ${POSTGRES_URL}
    username: ${USERNAME_DB}
    password: ${PASSWORD_DB}
  jpa:
    hibernate:
      ddl-auto: update #update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  #        envers:
  #          audit_table_suffix: _aud
  #          store_data_at_delete: true

  flyway:
    enabled: false
    locations: classpath:db/migration
    baseline-on-migrate: true
  #    baseline-version: 1
  main:
    allow-bean-definition-overriding: true

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${USERNAME_MAIL}
    password: ${PASSWORD_MAIL}
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

jwt:
  secretKey: ${JWT_SECRETKEY}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui
